DROP TABLE IF EXISTS autor CASCADE;
DROP TABLE IF EXISTS ksiazka CASCADE;
DROP TABLE IF EXISTS ksiazka_autor CASCADE;
DROP TABLE IF EXISTS wydanie CASCADE;
DROP TABLE IF EXISTS czytelnik CASCADE;
DROP TABLE IF EXISTS egzemplarz CASCADE;
DROP TABLE IF EXISTS egzemplarz_czytelnik CASCADE;